/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sevval_bilgin_project_reversi;

import static com.mycompany.sevval_bilgin_project_reversi.SevvalBilginData.userList;
import java.io.IOException;
import java.util.ConcurrentModificationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SevvalBilginSignInFrame extends javax.swing.JFrame {

    /**
     * Creates new form SevvalBilginSignInFrame
     */
    JFrame parent_frame;

    public SevvalBilginSignInFrame(JFrame parent_frame) {
        initComponents();
        this.parent_frame = parent_frame;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_sign_in_root = new javax.swing.JPanel();
        btn_user1_log_in1 = new javax.swing.JButton();
        btn_user1_sign_in1 = new javax.swing.JButton();
        txt_user1_mail1 = new javax.swing.JTextField();
        txt_user1_password1 = new javax.swing.JTextField();
        lbl_user1_mail1 = new javax.swing.JLabel();
        lbl_user1_password1 = new javax.swing.JLabel();
        password_user3 = new javax.swing.JPasswordField();
        lbl_user1_name1 = new javax.swing.JLabel();
        pnl_sign_in = new javax.swing.JPanel();
        lbl_sign_in_name = new javax.swing.JLabel();
        txt_sign_in_name = new javax.swing.JTextField();
        lbl_sign_in_mail = new javax.swing.JLabel();
        txt_sign_in_mail = new javax.swing.JTextField();
        lbl_sign_in_password = new javax.swing.JLabel();
        password_sign_in = new javax.swing.JPasswordField();
        lbl_sign_in_phone = new javax.swing.JLabel();
        lbl_sign_in_address = new javax.swing.JLabel();
        txt_sign_in_phone = new javax.swing.JTextField();
        scrollpane_sign_in_address = new javax.swing.JScrollPane();
        txt_sign_in_address = new javax.swing.JTextArea();
        btn_sign_in_sign_in = new javax.swing.JButton();
        btn_sign_in_cancel = new javax.swing.JButton();

        pnl_sign_in_root.setBackground(new java.awt.Color(255, 255, 255));
        pnl_sign_in_root.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ink Free", 1, 14))); // NOI18N
        pnl_sign_in_root.setPreferredSize(new java.awt.Dimension(270, 337));
        pnl_sign_in_root.setLayout(new java.awt.GridBagLayout());

        btn_user1_log_in1.setText("Log In");
        btn_user1_log_in1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user1_log_in1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 10, 0, 0);
        pnl_sign_in_root.add(btn_user1_log_in1, gridBagConstraints);

        btn_user1_sign_in1.setText("Sign  in");
        btn_user1_sign_in1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user1_sign_in1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        pnl_sign_in_root.add(btn_user1_sign_in1, gridBagConstraints);

        txt_user1_mail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_user1_mail1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 10, 0, 0);
        pnl_sign_in_root.add(txt_user1_mail1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        pnl_sign_in_root.add(txt_user1_password1, gridBagConstraints);

        lbl_user1_mail1.setText("Mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
        pnl_sign_in_root.add(lbl_user1_mail1, gridBagConstraints);

        lbl_user1_password1.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        pnl_sign_in_root.add(lbl_user1_password1, gridBagConstraints);

        password_user3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_user3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        pnl_sign_in_root.add(password_user3, gridBagConstraints);

        lbl_user1_name1.setText("User Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 10, 0, 0);
        pnl_sign_in_root.add(lbl_user1_name1, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        pnl_sign_in.setBackground(new java.awt.Color(255, 204, 204));
        pnl_sign_in.setPreferredSize(new java.awt.Dimension(411, 300));
        pnl_sign_in.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sign_in_name.setText("User Name");
        pnl_sign_in.add(lbl_sign_in_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, 30));

        txt_sign_in_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sign_in_nameActionPerformed(evt);
            }
        });
        pnl_sign_in.add(txt_sign_in_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 14, 115, -1));

        lbl_sign_in_mail.setText("Mail");
        pnl_sign_in.add(lbl_sign_in_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 48, 60, -1));
        pnl_sign_in.add(txt_sign_in_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 48, 111, -1));

        lbl_sign_in_password.setText("Password");
        pnl_sign_in.add(lbl_sign_in_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 131, 69, -1));

        password_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_sign_inActionPerformed(evt);
            }
        });
        pnl_sign_in.add(password_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 128, 111, -1));

        lbl_sign_in_phone.setText("Phone");
        pnl_sign_in.add(lbl_sign_in_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 91, 37, -1));

        lbl_sign_in_address.setText("Adress");
        pnl_sign_in.add(lbl_sign_in_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 162, 60, -1));
        pnl_sign_in.add(txt_sign_in_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 88, 111, -1));

        txt_sign_in_address.setColumns(20);
        txt_sign_in_address.setRows(5);
        scrollpane_sign_in_address.setViewportView(txt_sign_in_address);

        pnl_sign_in.add(scrollpane_sign_in_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 162, 180, -1));

        btn_sign_in_sign_in.setText("Sign  in");
        btn_sign_in_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_in_sign_inActionPerformed(evt);
            }
        });
        pnl_sign_in.add(btn_sign_in_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 260, -1, 28));

        btn_sign_in_cancel.setText("Cancel");
        btn_sign_in_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_in_cancelActionPerformed(evt);
            }
        });
        pnl_sign_in.add(btn_sign_in_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 258, -1, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnl_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_user1_log_in1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user1_log_in1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_user1_log_in1ActionPerformed

    private void btn_user1_sign_in1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user1_sign_in1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_user1_sign_in1ActionPerformed

    private void txt_user1_mail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_user1_mail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_user1_mail1ActionPerformed

    private void password_user3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_user3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_user3ActionPerformed

    private void txt_sign_in_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sign_in_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sign_in_nameActionPerformed

    private void password_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_sign_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_sign_inActionPerformed

    private void btn_sign_in_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign_in_sign_inActionPerformed
        try {
            SevvalBilginUsers newUser = new SevvalBilginUsers();

            // TODO add your handling code here:
            Pattern pattern = Pattern.compile("/^((\\w.*)@gmail.com)||(\\w.*)@hotmail.com$/", Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(txt_sign_in_mail.getText());
            boolean matchFound = matcher.find();
            if (matchFound) {
                newUser.mail = txt_sign_in_mail.getText();
            } else {
                JOptionPane.showConfirmDialog(rootPane, "mailin @gmail.com ya da @hotmail.com içermeli!", "warning", JOptionPane.INFORMATION_MESSAGE);
            }
            newUser.name = txt_sign_in_name.getText();

            newUser.phone = Integer.parseInt(txt_sign_in_phone.getText());
            newUser.password = password_sign_in.getText();
            newUser.address = txt_sign_in_address.getText();
            for (SevvalBilginUsers s : userList) {
                if (s.mail.compareTo(txt_sign_in_mail.toString()) == 0) {
                    JOptionPane.showMessageDialog(this, "Select another email!!");

                } else if (s.name.compareTo(txt_sign_in_name.toString()) == 0) {
                    JOptionPane.showMessageDialog(this, "Select another name!!");

                } else {
                    SevvalBilginData.AddUserToUserList(newUser);
                    SevvalBilginData.WriteUserListToFile();
                    JOptionPane.showMessageDialog(parent_frame, "User added!!");
                    this.parent_frame.setVisible(true);
                    this.dispose();
                }
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(parent_frame, "You should enter numbers!!");
        } catch (IOException ex) {
            Logger.getLogger(SevvalBilginSignInFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ConcurrentModificationException ex) {

        } catch (Exception ex) {
            Logger.getLogger(SevvalBilginSignInFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_sign_in_sign_inActionPerformed

    private void btn_sign_in_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign_in_cancelActionPerformed
        // TODO add your handling code here:
        this.parent_frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sign_in_cancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sign_in_cancel;
    private javax.swing.JButton btn_sign_in_sign_in;
    private javax.swing.JButton btn_user1_log_in1;
    private javax.swing.JButton btn_user1_sign_in1;
    private javax.swing.JLabel lbl_sign_in_address;
    private javax.swing.JLabel lbl_sign_in_mail;
    private javax.swing.JLabel lbl_sign_in_name;
    private javax.swing.JLabel lbl_sign_in_password;
    private javax.swing.JLabel lbl_sign_in_phone;
    private javax.swing.JLabel lbl_user1_mail1;
    private javax.swing.JLabel lbl_user1_name1;
    private javax.swing.JLabel lbl_user1_password1;
    private javax.swing.JPasswordField password_sign_in;
    private javax.swing.JPasswordField password_user3;
    private javax.swing.JPanel pnl_sign_in;
    private javax.swing.JPanel pnl_sign_in_root;
    private javax.swing.JScrollPane scrollpane_sign_in_address;
    private javax.swing.JTextArea txt_sign_in_address;
    private javax.swing.JTextField txt_sign_in_mail;
    private javax.swing.JTextField txt_sign_in_name;
    private javax.swing.JTextField txt_sign_in_phone;
    private javax.swing.JTextField txt_user1_mail1;
    private javax.swing.JTextField txt_user1_password1;
    // End of variables declaration//GEN-END:variables
}
