/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sevval_bilgin_project_reversi;


import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SevvalBilginLogInFrame extends javax.swing.JFrame {

    public static String user1_new_name = "User 1";
    public static String user2_new_name = "User 2";
    public static SevvalBilginUsers[] entered_users_list = new SevvalBilginUsers[2];

    /**
     * Creates new form SevvalBilginRegisterFrame
     */
    public SevvalBilginLogInFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_root_pnl = new javax.swing.JPanel();
        pnl_user1 = new javax.swing.JPanel();
        btn_login_user1_login = new javax.swing.JButton();
        btn_login_user1_signin = new javax.swing.JButton();
        txt_login_user1_mail = new javax.swing.JTextField();
        txt_login_user1_name = new javax.swing.JTextField();
        lbl_login_user1_mail = new javax.swing.JLabel();
        lbl_login_user1_password = new javax.swing.JLabel();
        password_login_user1 = new javax.swing.JPasswordField();
        lbl_login_user1_name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_user2 = new javax.swing.JPanel();
        btn_login_user2_login = new javax.swing.JButton();
        btn_login_user2_signin = new javax.swing.JButton();
        txt_login_user2_mail = new javax.swing.JTextField();
        txt_login_user2_name = new javax.swing.JTextField();
        lbl_login_user2_mail = new javax.swing.JLabel();
        lbl_login_user2_password = new javax.swing.JLabel();
        lbl_login_user2_user_name = new javax.swing.JLabel();
        password_login_user2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_root_pnl.setBackground(new java.awt.Color(255, 255, 204));
        pnl_root_pnl.setMinimumSize(new java.awt.Dimension(600, 337));
        pnl_root_pnl.setPreferredSize(new java.awt.Dimension(600, 337));
        pnl_root_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_user1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_user1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ink Free", 1, 14))); // NOI18N
        pnl_user1.setMinimumSize(new java.awt.Dimension(270, 337));
        pnl_user1.setPreferredSize(new java.awt.Dimension(270, 337));
        pnl_user1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_login_user1_login.setText("Log In");
        btn_login_user1_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_user1_loginActionPerformed(evt);
            }
        });
        pnl_user1.add(btn_login_user1_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 28));

        btn_login_user1_signin.setText("Sign  in");
        btn_login_user1_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_user1_signinActionPerformed(evt);
            }
        });
        pnl_user1.add(btn_login_user1_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, 28));

        txt_login_user1_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_user1_mailActionPerformed(evt);
            }
        });
        pnl_user1.add(txt_login_user1_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 157, 120, -1));
        pnl_user1.add(txt_login_user1_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 118, 120, -1));

        lbl_login_user1_mail.setText("Mail");
        pnl_user1.add(lbl_login_user1_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 160, 60, -1));

        lbl_login_user1_password.setText("Password");
        pnl_user1.add(lbl_login_user1_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 200, 69, -1));

        password_login_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_login_user1ActionPerformed(evt);
            }
        });
        pnl_user1.add(password_login_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, -1));

        lbl_login_user1_name.setText("User Name");
        pnl_user1.add(lbl_login_user1_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 120, 70, 19));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel1.setText("USER2 WILL MAKE");
        pnl_user1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 30));

        pnl_root_pnl.add(pnl_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 400));

        pnl_user2.setBackground(new java.awt.Color(0, 0, 0));
        pnl_user2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Ink Free", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnl_user2.setMinimumSize(new java.awt.Dimension(270, 337));
        pnl_user2.setPreferredSize(new java.awt.Dimension(270, 337));
        pnl_user2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_login_user2_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login_user2_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_user2_login.setText("Log In");
        btn_login_user2_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_user2_loginActionPerformed(evt);
            }
        });
        pnl_user2.add(btn_login_user2_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 270, -1, -1));

        btn_login_user2_signin.setBackground(new java.awt.Color(0, 0, 0));
        btn_login_user2_signin.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_user2_signin.setText("Sign  in");
        btn_login_user2_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_user2_signinActionPerformed(evt);
            }
        });
        pnl_user2.add(btn_login_user2_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 310, -1, -1));

        txt_login_user2_mail.setBackground(new java.awt.Color(0, 0, 0));
        txt_login_user2_mail.setForeground(new java.awt.Color(255, 255, 255));
        pnl_user2.add(txt_login_user2_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 170, 120, -1));

        txt_login_user2_name.setBackground(new java.awt.Color(0, 0, 0));
        txt_login_user2_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_login_user2_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_user2_nameActionPerformed(evt);
            }
        });
        pnl_user2.add(txt_login_user2_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 130, 120, -1));

        lbl_login_user2_mail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_login_user2_mail.setText("Mail");
        pnl_user2.add(lbl_login_user2_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 170, 83, 25));

        lbl_login_user2_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_login_user2_password.setText("Password");
        pnl_user2.add(lbl_login_user2_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 210, 62, 22));

        lbl_login_user2_user_name.setBackground(new java.awt.Color(0, 0, 0));
        lbl_login_user2_user_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_login_user2_user_name.setText("User Name");
        pnl_user2.add(lbl_login_user2_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 130, 80, 22));

        password_login_user2.setBackground(new java.awt.Color(0, 0, 0));
        password_login_user2.setForeground(new java.awt.Color(255, 255, 255));
        pnl_user2.add(password_login_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 210, 118, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("THE FIRST MOVE!!");
        pnl_user2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 30, -1, -1));

        pnl_root_pnl.add(pnl_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 310, 400));

        getContentPane().add(pnl_root_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 403));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int entered_users = 0;
    private void btn_login_user1_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_user1_loginActionPerformed
        // TODO add your handling code here:
        SevvalBilginUsers user1 = new SevvalBilginUsers();
        user1.setColorWhite();
        String name = txt_login_user1_name.getText();
        user1.setName(name);
        user1_new_name = txt_login_user1_name.getText();
        String mail = txt_login_user1_mail.getText();
        String password = password_login_user1.getText();
        boolean user1_isLogin = SevvalBilginData.Login(name, mail, password);
        if (user1_isLogin == true) {
            user1.name=name;
            user1.mail=mail;
            user1.setColorWhite();
            user1.password=password;
            entered_users++;
            SevvalBilginLogInFrame.entered_users_list[0] = user1;
            if (entered_users == 2) {
                SevvalBilginGameSceneFrame game_frame = new SevvalBilginGameSceneFrame();
                game_frame.setVisible(true);

            } else if (entered_users == 1) {

                txt_login_user1_mail.setText("");
                txt_login_user1_name.setText("");
                password_login_user1.setText("");
                JOptionPane.showMessageDialog(rootPane, "Waiting for the second user", "Wait", JOptionPane.OK_OPTION);
//                

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "User can't found,plz rewrite your informations truly", "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btn_login_user1_loginActionPerformed

    private void btn_login_user1_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_user1_signinActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SevvalBilginSignInFrame frm_sign_in = new SevvalBilginSignInFrame(this);
        frm_sign_in.setVisible(true);
    }//GEN-LAST:event_btn_login_user1_signinActionPerformed

    private void txt_login_user1_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_user1_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_user1_mailActionPerformed

    private void password_login_user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_login_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_login_user1ActionPerformed

    private void txt_login_user2_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_user2_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_user2_nameActionPerformed

    private void btn_login_user2_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_user2_signinActionPerformed
        // TODO add your handling code here:
        SevvalBilginLogInFrame frame_log_in = new SevvalBilginLogInFrame();

        frame_log_in.setVisible(false);
        new SevvalBilginSignInFrame(frame_log_in).setVisible(true);

    }//GEN-LAST:event_btn_login_user2_signinActionPerformed

    private void btn_login_user2_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_user2_loginActionPerformed
        // TODO add your handling code here:
       
        SevvalBilginUsers user2 = new SevvalBilginUsers();
        user2.setColorBlack();
        String name = txt_login_user2_name.getText();
        user2_new_name = txt_login_user2_name.getText();
        String mail = txt_login_user2_mail.getText();
        String password = password_login_user2.getText();
        boolean user2_isLogin = SevvalBilginData.Login(name, mail, password);
        if (user2_isLogin == true) {
            entered_users++;
            SevvalBilginLogInFrame.entered_users_list[1] = user2;
            if (entered_users == 2) {

                SevvalBilginGameSceneFrame game_frame = new SevvalBilginGameSceneFrame();
                game_frame.setVisible(true);

            } else if (entered_users == 1) {

                txt_login_user2_mail.setText("");
                txt_login_user2_name.setText("");
                password_login_user2.setText("");
                JOptionPane.showMessageDialog(rootPane, "Waiting for the second user", "Wait", JOptionPane.OK_OPTION);
//                

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Plz enter all areas", "Error", JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_btn_login_user2_loginActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login_user1_login;
    private javax.swing.JButton btn_login_user1_signin;
    private javax.swing.JButton btn_login_user2_login;
    private javax.swing.JButton btn_login_user2_signin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_login_user1_mail;
    private javax.swing.JLabel lbl_login_user1_name;
    private javax.swing.JLabel lbl_login_user1_password;
    private javax.swing.JLabel lbl_login_user2_mail;
    private javax.swing.JLabel lbl_login_user2_password;
    private javax.swing.JLabel lbl_login_user2_user_name;
    private javax.swing.JPasswordField password_login_user1;
    private javax.swing.JPasswordField password_login_user2;
    private javax.swing.JPanel pnl_root_pnl;
    private javax.swing.JPanel pnl_user1;
    private javax.swing.JPanel pnl_user2;
    private javax.swing.JTextField txt_login_user1_mail;
    private javax.swing.JTextField txt_login_user1_name;
    private javax.swing.JTextField txt_login_user2_mail;
    private javax.swing.JTextField txt_login_user2_name;
    // End of variables declaration//GEN-END:variables
}
