/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sevval_bilgin_project_reversi;
import java.io.IOException;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class SevvalBilginScoresTable extends javax.swing.JFrame {

    /**
     * Creates new form SevvalBilginScoresTable
     */
    public static DefaultTableModel tbl_scores_model = new DefaultTableModel();

    public SevvalBilginScoresTable() throws IOException {

        initComponents();
        table_scores.setModel(tbl_scores_model);
        tbl_scores_model.setColumnIdentifiers(new Object[]{"User name", "Score"});
        File scores = new File("scoresList.txt");
        scores.createNewFile();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane_scorestable = new javax.swing.JScrollPane();
        table_scores = new javax.swing.JTable();
        btn_scores_table_delete = new javax.swing.JButton();
        btn_scores_table_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table_scores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "Scores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_scores.setCellSelectionEnabled(true);
        table_scores.setDragEnabled(true);
        scrollpane_scorestable.setViewportView(table_scores);
        if (table_scores.getColumnModel().getColumnCount() > 0) {
            table_scores.getColumnModel().getColumn(0).setResizable(false);
            table_scores.getColumnModel().getColumn(1).setResizable(false);
        }

        btn_scores_table_delete.setText("Delete");
        btn_scores_table_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scores_table_deleteActionPerformed(evt);
            }
        });

        btn_scores_table_cancel.setText("Cancel");
        btn_scores_table_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scores_table_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_scorestable, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_scores_table_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_scores_table_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_scorestable, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_scores_table_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btn_scores_table_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_scores_table_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scores_table_deleteActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, " Do you want to delete your score??", "Question", JOptionPane.YES_NO_CANCEL_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            String given_pass = JOptionPane.showInputDialog(rootPane, "If you want to delete your score please enter your password");
            for (SevvalBilginUsers user : SevvalBilginData.scoresList) {
                for (SevvalBilginUsers us : SevvalBilginData.userList) {
                    if (user.name.compareTo(us.name) == 0) {
                        user.password = us.password;
                        if (user.password.compareTo(given_pass) == 0) {

                            SevvalBilginScoresTable.tbl_scores_model.removeRow(table_scores.getSelectedRow());
                            table_scores.revalidate();
                        }
                    }
                }
            }
            for (int i = 0; i < tbl_scores_model.getRowCount(); i++) {
                if (tbl_scores_model.getValueAt(i, 0).toString().compareTo(given_pass) == 0) {

                    SevvalBilginScoresTable.tbl_scores_model.getDataVector().removeElementAt(i);
                    table_scores.revalidate();
                }
            }
        }

//              
    }//GEN-LAST:event_btn_scores_table_deleteActionPerformed

    private void btn_scores_table_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scores_table_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SevvalBilginGameSceneFrame GM = new SevvalBilginGameSceneFrame();
        GM.setVisible(true);
    }//GEN-LAST:event_btn_scores_table_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_scores_table_cancel;
    private javax.swing.JButton btn_scores_table_delete;
    private javax.swing.JScrollPane scrollpane_scorestable;
    private javax.swing.JTable table_scores;
    // End of variables declaration//GEN-END:variables
}
